import Navbar from "@/components/Navbar";
import { Spinner } from "@/components/ui/spinner";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "Product Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Suspense fallback={<Spinner text="Loading ...." />}>
          <Toaster />
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              {children}
            </ThemeProvider>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
